remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

title: "PYU"
description: "Python Utilities & Automation Tools"

# Enable the navigation bar
header_pages:
  - index.md
  - projects.md
  - documentation.md
  - about.md
