remote_theme: mmistakes/minimal-mistakes
title: PYU
description: Python Utilities & Automation Tools

plugins:
  - jekyll-include-cache

nav:
  - Home: index.md
  - Projects: projects.md
  - Documentation: documentation.md
  - About: about.md
  
